export const INITIAL_MARGIN = 20,
  PIE_RADIUS = 160,
  DONUT_STROKE_SIZE = 16,
  SIDE_MARGIN = 120,
  WIDTH = (PIE_RADIUS + SIDE_MARGIN) * 2,
  MARGIN = 150,
  DONUT_LINE_LENGTH = 4,
  TEXT_MARGIN = 20;
